Repository GenoImel/The-Mechanical-Forest, pull requests merged in 2023-10, with the labels that each got.

#132 Make Fields Private and Use Properties In `PartyMemberController` and Related Classes
  Assets/Scripts/Runtime/Controllers/PartyMemberBattle/PartyMemberController.cs
  Assets/Scripts/Runtime/Controllers/PartyMemberBattle/PartyMemberResourceHandler.cs
  Assets/Scripts/Runtime/Controllers/PartyMemberBattle/PartyMemberStatHandler.cs
  Assets/Scripts/Runtime/Converters/PartyMemberConverter.cs
Labels: enhancement

#138 First implementation of the Debugger MonoSystem
  Assets/Prefabs/MonoSystems/Debugger.meta
  Assets/Prefabs/MonoSystems/Debugger/DebuggerMonoSystem.prefab
  Assets/Prefabs/MonoSystems/Debugger/DebuggerMonoSystem.prefab.meta
  Assets/Resources/GameManager.prefab
  Assets/Scripts/Runtime/AkashicGameManager.cs
  Assets/Scripts/Runtime/MonoSystems/Debugger.meta
  Assets/Scripts/Runtime/MonoSystems/Debugger/DebuggerMonoSystem.cs
  Assets/Scripts/Runtime/MonoSystems/Debugger/DebuggerMonoSystem.cs.meta
  Assets/Scripts/Runtime/MonoSystems/Debugger/IDebuggerMonoSystem.cs
  Assets/Scripts/Runtime/MonoSystems/Debugger/IDebuggerMonoSystem.cs.meta
Labels: enhancement

#134 Enforced Character Limit for Save Slot Name
  Assets/Prefabs/Controllers/SaveMenu/SaveSlot.prefab
  Assets/ScriptableObjects/ConfigBase/ConfigBaseData.cs
  Assets/Scripts/Editor/ConfigBaseDataEditor.cs
  Assets/Scripts/Runtime/Controllers/SaveMenu/FileNameRequestPanel.cs
  Assets/Scripts/Runtime/MonoSystems/Config/ConfigMonoSystem.cs
  Assets/Scripts/Runtime/MonoSystems/Config/IConfigMonoSystem.cs
Labels: bug

#135 Refactored Save File/Folder and Slot Field Names
  Assets/Prefabs/Controllers/SaveMenu/SaveMenuController.prefab
  Assets/Prefabs/Controllers/SaveMenu/SaveMenuPanel.prefab
  Assets/Prefabs/Controllers/SaveMenu/SaveSlotContainer.prefab
  Assets/Prefabs/Controllers/SaveMenu/SaveSlotContainer.prefab.meta
  Assets/Resources/Game/DefaultConfig.asset
  Assets/ScriptableObjects/ConfigBase/ConfigBaseData.cs
  Assets/Scripts/Editor/ConfigBaseDataEditor.cs
  Assets/Scripts/Runtime/Controllers/SaveMenu/SaveMenuController.cs
  Assets/Scripts/Runtime/Controllers/SaveMenu/SaveSlot.cs
  Assets/Scripts/Runtime/Controllers/SaveMenu/SaveSlotContainer.cs
  Assets/Scripts/Runtime/Controllers/SaveMenu/SaveSlotContainer.cs.meta
  Assets/Scripts/Runtime/MonoSystems/Config/ConfigMonoSystem.cs
  Assets/Scripts/Runtime/MonoSystems/Config/IConfigMonoSystem.cs
  Assets/Scripts/Runtime/MonoSystems/Save/SaveMonoSystem.cs
Labels: enhancement

#144 PartyMember Handlers moved to Child Objects
  Assets/Prefabs/PartyMembers/Airy.prefab
  Assets/Prefabs/PartyMembers/Benoit.prefab
  Assets/Prefabs/PartyMembers/Conrad.prefab
  Assets/Prefabs/PartyMembers/Default.prefab
  Assets/Prefabs/PartyMembers/Lena.prefab
  Assets/Scripts/Runtime/Controllers/PartyMemberBattle/PartyMemberResourceHandler.cs
  Assets/Scripts/Runtime/Controllers/PartyMemberBattle/PartyMemberStatHandler.cs
Labels: enhancement

#142 Updated Documentation to Reflect New Architecture
  Documentation~/CodingStandards.md
  Documentation~/CoreArchitecture.md
Labels: documentation

#147 Feature/stat handler responsibility refactor
  Assets/Scripts/Runtime/Controllers/PartyMemberBattle/PartyMemberStatHandler.cs
  Assets/Scripts/Runtime/Converters/PartyMemberConverter.cs
  Assets/Scripts/Runtime/Stats.meta
  Assets/Scripts/Runtime/Stats/AttackStats.cs
  Assets/Scripts/Runtime/Stats/AttackStats.cs.meta
  Assets/Scripts/Runtime/Stats/DefenseStats.cs
  Assets/Scripts/Runtime/Stats/DefenseStats.cs.meta
Labels: enhancement

#172 Full Canvas Resolution Overhaul
  Assets/Prefabs/Controllers/BattleCurtain/BattleCurtainController.prefab
  Assets/Prefabs/Controllers/BattleHud/ActionLineItem.prefab
  Assets/Prefabs/Controllers/BattleHud/ActionLineItem.prefab.meta
  Assets/Prefabs/Controllers/BattleHud/BattleHudController.prefab
  Assets/Prefabs/Controllers/BattleHud/PartyMemberBattleProfile.prefab
  Assets/Prefabs/Controllers/BattleHud/PartyMemberBattleProfile.prefab.meta
  Assets/Prefabs/Controllers/BattleHud/TimelineSprite.prefab
  Assets/Prefabs/Controllers/BattleHud/TimelineSprite.prefab.meta
  Assets/Prefabs/Controllers/DungeonHud/DungeonHudController.prefab
  Assets/Prefabs/Controllers/DungeonHud/PartyMemberDungeonProfile.prefab
  Assets/Prefabs/Controllers/GameOver/GameOverController.prefab
  Assets/Prefabs/Controllers/InventoryMenu/InventoryMenuController.prefab
  Assets/Prefabs/Controllers/LoadingCurtain/LoadingCurtainController.prefab
  Assets/Prefabs/Controllers/LootScreen/AccessoriesLootContainer.prefab
  Assets/Prefabs/Controllers/LootScreen/AccessoriesLootContainer.prefab.meta
  Assets/Prefabs/Controllers/LootScreen/ItemsLootContainer.prefab
  Assets/Prefabs/Controllers/LootScreen/ItemsLootContainer.prefab.meta
  Assets/Prefabs/Controllers/LootScreen/LootScreenController.prefab
  Assets/Prefabs/Controllers/MainMenu/MainMenuController.prefab
  Assets/Prefabs/Controllers/OptionsMenu/OptionsMenuController.prefab
  Assets/Prefabs/Controllers/PartyMenu/PartyMenuController.prefab
  Assets/Prefabs/Controllers/SaveMenu/BackButton.prefab
  Assets/Prefabs/Controllers/SaveMenu/BackButton.prefab.meta
  Assets/Prefabs/Controllers/SaveMenu/FileNameRequestPanel.prefab
  Assets/Prefabs/Controllers/SaveMenu/SaveMenuController.prefab
  Assets/Prefabs/Controllers/SaveMenu/SaveMenuPanel.prefab
  Assets/Prefabs/Controllers/SaveMenu/SaveSlot.prefab
  Assets/Prefabs/Controllers/SaveMenu/SaveSlot.prefab.meta
  Assets/Prefabs/Controllers/SaveMenu/SaveSlotContainer.prefab
  Assets/Prefabs/Controllers/Story/DialogueEntry.prefab
  Assets/Prefabs/Controllers/Story/DialoguePanel.prefab
  Assets/Prefabs/Controllers/Story/StoryController.prefab
  Assets/Prefabs/Controllers/Story/StoryEventLogPanel.prefab
  Assets/Prefabs/Controllers/Story/StoryEventSkipPanel.prefab
  Assets/Prefabs/Controllers/VictoryScreen/CharacterExperienceCounter.prefab
  Assets/Prefabs/Controllers/VictoryScreen/CharacterExperienceCounter.prefab.meta
  Assets/Prefabs/Controllers/VictoryScreen/VictoryScreenController.prefab
  Assets/Resources/GameManager.prefab
  Assets/Scenes/BattleScene.unity
  Assets/Scenes/ExplorationScene.unity
  Assets/Scenes/MainMenuScene.unity
Labels: enhancement
